# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47a77ef7fff2d799119ca99a3a6a39ac34e8d25a787277fd1c8322d28e0d565cd4a862ad81a3fd1eb43f0a3d7b1ddc391acce30c4beb587609d2563e117602dc

test:
  secret_key_base: 2c03c3408d216497f54dba245c57d80e2c5800d3fa11a69165ff37238401ee2167e9212f32bc3a59f00ae40ab62c2bbefff50364541a5e78a69a8ac4d20ba4a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
